target("Hawl-Renderer")
    set_kind("shared")
    add_packages("eastl")
    add_packages("spdlog")
    add_packages("mimalloc")
    add_packages("tbb")
    add_includedirs("interface", {public = true})
    add_includedirs("include")
    add_files("src/*.cpp")
target_end()